"""
This file is part of the hatchling-based build system
See pyproject.toml
"""

import sys
import sysconfig
from pathlib import Path

from hatchling.metadata.plugin.interface import MetadataHookInterface
from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CustomMetadataHook(MetadataHookInterface):
    """
    Our custom code to get the library version
    """

    def update(self, metadata: dict):
        py_dir = Path(self.root).resolve(strict=True)
        version_file = py_dir.parent.parent.parent / "version_definition.py"

        locals = {}
        exec(open(version_file).read(), globals(), locals)

        # Update the [project] table metadata
        metadata["version"] = locals["version_full"]

        # Write the version to a file in the package
        with open(py_dir / "spectral_wave_data/version.py", "w") as f:
            f.write('"""\nThis file is automatically generated by the build system\n"""\n')
            for key in ["version_short", "version_full"]:
                f.write(f'{key} = "{locals[key]}"\n')


class CustomBuildHook(BuildHookInterface):
    """
    Our custom code to include the compiled library in the wheel
    and to set the appropriate wheel tag
    """

    def initialize(self, version: str, build_data: dict):
        ################################
        # Bundle the compiled library
        ################################

        # Make a list of possible paths to the compiled library (platform-dependent)
        lib_search_paths: list[Path] = []
        cmake_dir = Path(self.root).resolve(strict=True) / "Cmake"
        if sys.platform.startswith("linux"):
            lib_search_paths.append(cmake_dir / "Build_Linux/libSpectralWaveData.so")
        elif sys.platform.startswith("win"):
            lib_search_paths.append(cmake_dir / "Build_Win64/Release/SpectralWaveData.dll")
            lib_search_paths.append(cmake_dir / "Build_Win64/Debug/SpectralWaveData.dll")
            lib_search_paths.append(cmake_dir / "Build_Win64/SpectralWaveData.dll")
        else:
            raise RuntimeError(f"Unsupported build platform: {sys.platform}")

        # Search for the compiled library in the specified paths
        for candidate in lib_search_paths:
            if candidate.exists():
                lib = candidate
                self.app.display_success(f"Found the compiled library at {candidate}")
                break
            else:
                self.app.display_info(f"Could not find the compiled library at {candidate}")
        else:
            self.app.abort(
                "Could not find the compiled library. "
                "Please ensure the Fortran build step has been run successfully."
            )

        build_data["force_include"][str(lib.resolve(strict=True))] = (
            f"spectral_wave_data/{lib.name}"
        )

        ################################
        # Setup the Wheel metadata
        ################################

        # We include a compiled library so the wheel is not pure Python
        build_data["pure_python"] = False

        # Create the tag for the Wheel file
        # See https://peps.python.org/pep-0425/
        # Should end up with
        # - py3-none-linux_x86_64
        # - py3-none-win_amd64
        # The "none" is because we don't have any ABI requirements since we
        # use ctypes and not the Python C API
        python_requirement = "py3"
        abi_requirement = "none"
        platform_requirement = sysconfig.get_platform().replace("-", "_").replace(".", "_")
        build_data["tag"] = f"{python_requirement}-{abi_requirement}-{platform_requirement}"
