name: "Build Python Wheel on Linux"

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Ubuntu 20.04 is the oldest Ubuntu LTS with GCC >= 9
        os: [ubuntu-20.04]
  
    steps:
      - uses: actions/checkout@v4

      - name: Install the build toolchain
        run: |
          sudo apt update
          sudo apt install -y cmake gfortran
  
      - name: Compile the SWD Fortran library
        run: |
          cd src/api/python/Cmake
          bash ./CMakeBuild_Linux.bash

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
          python-version: 3.13
          enable-cache: true

      - name: Build wheel
        run: |
          cd src/api/python

          # Install auditwheel and any other dependencies
          uv sync --only-group=build

          # Create the wheel file (can also use "pip wheel .")
          # The file ends up in the "dist/" directory
          uv build --wheel

      - name: Auditwheel repair
        run: |
          cd src/api/python

          # Show the minimum manylinux tag on this system
          uv run auditwheel show dist/*.whl

          # Make the manylinux wheel
          # The file ends up in the "wheelhouse/" directory
          uv run auditwheel repair dist/*.whl

      - name: Upload Python wheels
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}
          path: src/api/python/wheelhouse
