name: "Release Python Wheel on Windows"

# For testing the workflow
# on: [push]

# Run when a release is published on GitHub or when manually started
on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  python_version_test: "3.12"

jobs:
  build_wheel:
    uses: ./.github/workflows/python_wheel_windows.yml
    secrets: inherit

  release_wheel:
    name: Release the Windows wheel
    needs: build_wheel
    runs-on: windows-2025

    # Specifying a GitHub environment is optional, but strongly encouraged
    # The environment must be created on GitHub (see PyPI trusted publishing docs)
    environment: pypi

    steps:
      - uses: actions/checkout@v7

      - name: Download the wheel artifact we just built and uploaded
        uses: actions/download-artifact@v8
        with:
          path: ./downloaded-wheels

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.25"  # Latest version of uv at time of commit, from 2026-06-26
          python-version: 3.14
          enable-cache: true

      - name: Install the wheel
        shell: powershell
        run: |
          cd tests\python
          
          Get-ChildItem -Path ../../downloaded-wheels -Recurse -Force
          $wheel = Get-ChildItem -Path ../../downloaded-wheels/python_wheel_for_win_amd64/*.whl |
            Select-Object -Expand FullName
          Write-Output "Found wheel file at: $wheel"
          Write-Output "WHEEL_FILE=$wheel" >> $env:GITHUB_ENV

          # Create a virtual environment with the oldest supported Python version
          uv venv .venv_release --clear --no-project --seed --python ${{ env.python_version_test }}
          .\.venv_release\Scripts\Activate.ps1

          # Install the test dependencies and then the newly built manylinux wheel
          pip install -r requirements_tests.txt
          pip install $wheel

          # Show the installed package version
          swd_meta --version

      - name: Test the wheel (full suite of tests)
        run: |
          cd tests/python
          .\.venv_release\Scripts\Activate.ps1

          # Run all unit tests
          python -m pytest -v

      - name: Publish the wheel to PyPI
        run: uv publish --trusted-publishing=always --no-config $env.WHEEL_FILE
