name: "Build Python Wheel on Linux"

on: [push, pull_request]

env:
  python_version_build: "3.14"
  python_version_test: "3.12"

jobs:
  build_wheel:
    name: Build oldest supported manylinux wheel
    runs-on: ubuntu-latest
    #container: quay.io/pypa/manylinux2014_x86_64  # Fails to run on GitHub Actions, too old libc
    container: quay.io/pypa/manylinux_2_28_x86_64  # GCC version 14, Redhat 8 / Ubuntu 18.10
    
    steps:
      - uses: actions/checkout@v7

      - name: Compile the SWD Fortran library
        run: |
          cd src/api/python/Cmake
          bash ./CMakeBuild_Linux.bash

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.25"  # Latest version of uv at time of commit, from 2026-06-26
          python-version:  ${{ env.python_version_build }}
          enable-cache: true

      - name: Build wheel
        run: |
          cd src/api/python

          # Install auditwheel and any other dependencies
          uv sync --only-group=build

          # Create the wheel file (can also use "pip wheel .")
          # The file ends up in the "dist/" directory
          uv build --wheel

      - name: Auditwheel repair
        run: |
          cd src/api/python

          # Show the minimum manylinux tag on this system
          uv run auditwheel show dist/*.whl

          # Make the manylinux wheel
          # The file ends up in the "wheelhouse/" directory
          uv run auditwheel repair dist/*.whl

          # Store path to the wheel file in an environment variable for later steps
          wheel="$(realpath wheelhouse/*.whl)"
          echo -e "\n\nFound wheel file at: ${wheel}"
          echo "WHEEL_FILE=${wheel}" >> $GITHUB_ENV
          echo "WHEEL_FILE_BASENAME=$(basename ${wheel})" >> $GITHUB_ENV

      - name: Install the wheel
        run: |
          cd tests/python

          # Create a virtual environment with the oldest supported Python version
          uv venv .venv --clear --no-project --seed --python ${{ env.python_version_test }}
          source .venv/bin/activate

          # Install the test dependencies and then the newly built manylinux wheel
          pip install -r requirements_tests.txt
          pip install "${WHEEL_FILE}"

          # Show the installation information with console scripts
          pip show --verbose spectral_wave_data
          ls -lh .venv/bin
          pwd
          echo "PATH: $PATH"

          # Show the installed package version
          python -c "import spectral_wave_data; print(spectral_wave_data.version_full)"
          swd_meta --version

      - name: Test the wheel
        run: |
          cd tests/python
          source .venv/bin/activate

          # Run a subset of the tests to verify that the wheel is functional
          export SWD_TEST_TYPE=quick
          python -m pytest -v

      - name: Upload the newly built Python wheel for manylinux_2_28_x86_64 to GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WHEEL_FILE_BASENAME }}
          path: ${{ env.WHEEL_FILE }}
