name: 'Install Intel oneAPI Fortran Compiler (ifx) on Windows'
description: 'Installs Intel oneAPI Fortran Compiler (ifx) on Windows and uses cacheing to speed up subsequent runs.'

inputs:
  download_path:
    description: 'Lat part of the download URL.'
    required: true
    default: 'b00ef14b-e999-414f-8649-cf5ac754eafc/intel-fortran-essentials-2025.2.0.510_offline.exe'
  download_dir:
    description: 'Path to the directory where the oneAPI installer will be downloaded.'
    required: true
    default: "D:\\MyOneAPI\\downloads"
  log_dir:
    description: 'Path to the directory where the oneAPI installer logs are stored.'
    required: true
    default: "D:\\MyOneAPI\\installer_logs"
  extract_dir:
    description: 'Path to the directory where the oneAPI installer will be extracted.'
    required: true
    default: "D:\\MyOneAPI\\extracted"
  install_dir:
    description: 'Path to the directory where the oneAPI bundle will be installed. This directory is cached to speed up subsequent runs.'
    required: true
    default: "D:\\MyOneAPI\\install"

outputs:
  install_dir:
    description: "The installation directory of Intel oneAPI Fortran Compiler (ifx)."
    value: ${{ inputs.install_dir }}
  compiler_path:
    description: 'Path to the Intel oneAPI Fortran Compiler (ifx) executable.'
    value: "${{ inputs.install_dir }}\\compiler\\2025.2\\bin\\ifx.exe"

runs:
  using: "composite"
  steps:
    # We cache the Intel oneAPI installation directory, it can take a looong time
    # to download and install it, especially on the C: drive, D: drive is faster
    # - Downloading the installer takes about 20 seconds
    # - Running the installer takes about 15 minutes !!! (on the C: drive, 12-14 on the D: drive)
    - name: Try to load the oneAPI Fortran Compiler installation from cache
      id: cache-oneAPI-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.install_dir }}
        # The key can be anything, but must change if the contents of the directory changes
        key: path=${{ inputs.install_dir }};version=${{ inputs.download_path }}

    - name: Make oneAPI installation directory structure (if not already installed)
      if: steps.cache-oneAPI-restore.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        # Stop the script when a cmdlet or a native command fails
        $ErrorActionPreference = 'Stop'
        $PSNativeCommandUseErrorActionPreference = $true

        # Create directories for the OneAPI installation
        # (Installer seems to fail silently if some of these directories are missing)
        New-Item -Path '${{ inputs.download_dir }}' -ItemType Directory -Force
        New-Item -Path '${{ inputs.log_dir }}'      -ItemType Directory -Force
        New-Item -Path '${{ inputs.extract_dir }}'  -ItemType Directory -Force
        New-Item -Path '${{ inputs.install_dir }}'  -ItemType Directory -Force

        Get-ChildItem -Path '${{ inputs.install_dir }}\..' -Recurse -Force

    - name: Download the Intel oneAPI Fortran Compiler (if not already installed)
      if: steps.cache-oneAPI-restore.outputs.cache-hit != 'true'
      shell: powershell
      working-directory: ${{ inputs.download_dir }}
      run: |
        # Stop the script when a cmdlet or a native command fails
        $ErrorActionPreference = 'Stop'
        $PSNativeCommandUseErrorActionPreference = $true

        $downloadUrl = 'https://registrationcenter-download.intel.com/akdlm/IRC_NAS/${{ inputs.download_path }}'
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri $downloadUrl -OutFile '${{ inputs.download_dir }}\intel-fortran-installer.exe'

        # Show the download directory contents
        Get-ChildItem -Path '${{ inputs.download_dir }}' -Recurse -Force

    - name: Install the Intel oneAPI Fortran Compiler (if not already installed)
      if: steps.cache-oneAPI-restore.outputs.cache-hit != 'true'
      shell: cmd
      working-directory: ${{ inputs.download_dir }}
      run: |
        ECHO Loading Visual Studio environment variables
        CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64

        ECHO .....................................................................................
        ECHO ..... Listing Intel oneAPI installer ................................................
        TIME /T
        .\intel-fortran-installer.exe -s -a --list-products
        TIME /T

        ECHO .....................................................................................
        ECHO ..... Running Intel oneAPI installer ................................................
        TIME /T
        .\intel-fortran-installer.exe ^
          --log "${{ inputs.log_dir }}\installer_extraction.log" ^
          --extract-folder "${{ inputs.extract_dir }}" ^
          -s -a --silent --eula accept ^
          --install-dir "${{ inputs.install_dir }}" ^
          --log-dir "${{ inputs.log_dir }}"
        TIME /T
        ECHO "............. DONE! ......................"

        SET INSTALLER_ERROR_CODE=%ERRORLEVEL%
        IF %INSTALLER_ERROR_CODE% NEQ 0 (
          ECHO "ERROR occurred in Intel oneAPI Fortran Compiler installation!"
        ) ELSE (
          ECHO "Intel oneAPI Fortran Compiler installation completed successfully"
        )

        ECHO .....................................................................................
        ECHO ..... The top-level log is found below ..............................................
        ECHO .....................................................................................
        TYPE "${{ inputs.log_dir }}\installer_extraction.log"
        ECHO .....................................................................................

        EXIT /B %INSTALLER_ERROR_CODE%

    - name: Save the Intel oneAPI Fortran Compiler installation to cache (if newly installed)
      if: steps.cache-oneAPI-restore.outputs.cache-hit != 'true'
      id: cache-oneAPI-save
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.install_dir }}
        key: ${{ steps.cache-oneAPI-restore.outputs.cache-primary-key }}

    - name: Set environmental variables
      shell: cmd
      run: |
        ECHO FC=ifx >> "%GITHUB_ENV%"
        ECHO CC=cl >> "%GITHUB_ENV%"
